$$f(w_1, w_2) = 0.1w_1^2 + 2w_2^2 \;\;\;\;\;\;\;(1)$$

In [48]:
import numpy as np

In [49]:
def df_w(w):
    """
    Thực hiện tính gradient của dw1 và dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW -- np.array [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    """

    dw1 = 2 * 0.1 * w[0]
    dw2 = 2 * 2 * w[1]

    dW = np.array([dw1, dw2])


    return dW

In [50]:
def Adam(W, dW, lr, V, S, beta1, beta2, t):
    """
    Thực hiện thuật tóan Adam để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    V -- np.array: [v1, v2] Exponentially weighted averages gradients
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients
    beta1 -- float: hệ số long-range average cho V
    beta2 -- float: hệ số long-range average cho S
    t -- int: lần thứ t update (bắt đầu bằng 1)
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    V -- np.array: [v1, v2] Exponentially weighted averages gradients sau khi đã cập nhật
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients sau khi đã cập nhật
    """
    epsilon = 1e-6
    #################### YOUR CODE HERE ####################
    V = beta1 * V + (1 - beta1) * dW 

    S = beta2 * S + (1 - beta2) * (dW ** 2)

    V_corr = V / (1 - beta1)

    S_corr = S / (1 - beta2)

    W = W - lr * V_corr / (np.sqrt(S_corr) + epsilon)
    ########################################################
    return W, V, S

In [51]:
def train_p1(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # initial
    W = np.array([-5, -2], dtype=np.float32)
    V = np.array([0, 0], dtype=np.float32)
    S = np.array([0, 0], dtype=np.float32)
    results = [W]
    #################### YOUR CODE HERE ####################
    # Tạo vòng lặp theo số lần epochs
    # tìm gradient dW gồm dw1 và dw2
    # dùng thuật toán optimization cập nhật w1, w2, s1, s2, v1, v2
    # append cặp [w1, w2] vào list results
    # các bạn lưu ý mỗi lần lặp nhớ lấy t (lần thứ t lặp) và t bất đầu bằng 1
    for epoch in range(epochs):
        dW = df_w(W)
        W, V, S = optimizer(W, dW, lr, V, S, beta1=0.9, beta2=0.999, t=epoch+1)
        results.append(W)

    return results

In [52]:
train_p1(Adam, lr=0.2, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.8000002 , -1.80000002]),
 array([-4.53157446, -1.53234021]),
 array([-4.2198145 , -1.22391458]),
 array([-3.87886593, -0.8920874 ]),
 array([-3.5184822 , -0.55167136]),
 array([-3.14612788, -0.21734608]),
 array([-2.7679101 ,  0.09556942]),
 array([-2.38906471,  0.37175056]),
 array([-2.01423269,  0.5978378 ]),
 array([-1.64762053,  0.76489708]),
 array([-1.29308728,  0.8698814 ]),
 array([-0.95417995,  0.91525602]),
 array([-0.63413034,  0.90733373]),
 array([-0.33582336,  0.85443713]),
 array([-0.06174675,  0.76556849]),
 array([0.18606706, 0.64967888]),
 array([0.40609556, 0.51535336]),
 array([0.59736657, 0.37070313]),
 array([0.75947608, 0.22331396]),
 array([0.89257921, 0.08016373]),
 array([ 0.99735438, -0.05252633]),
 array([ 1.07494495, -0.16949778]),
 array([ 1.12688525, -0.2666743 ]),
 array([ 1.15501888, -0.34133181]),
 array([ 1.16141666, -0.39216583]),
 array([ 1.14829976, -0.41923376]),
 array([ 1.11797166, -0.42378827]),
 ar